Repository prgrms-web-devcourse-final-project/WEB5_7_OronaminC_BE, pull requests merged in 2025-07, with the labels that each got.

#11 [Feat]: 회원 API 구현
  .gitignore
  build.gradle
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/member/controller/MemberController.java
  src/main/java/com/oronaminc/join/member/domain/Member.java
  src/main/java/com/oronaminc/join/member/dto/GuestLoginRequest.java
  src/main/java/com/oronaminc/join/member/dto/GuestLoginResponse.java
  src/main/java/com/oronaminc/join/member/dto/SessionInfoResponse.java
  src/main/java/com/oronaminc/join/member/repository/MemberJpaRepository.java
  src/main/java/com/oronaminc/join/member/security/AuthController.java
  src/main/java/com/oronaminc/join/member/security/AuthService.java
  src/main/java/com/oronaminc/join/member/security/MemberDetails.java
  src/main/java/com/oronaminc/join/member/security/SecurityConfig.java
  src/main/java/com/oronaminc/join/member/service/MemberService.java
  src/main/resources/application.properties
Labels: feat

#16 feat : 질문 생성 소켓 api 구현
  .gitignore
  src/main/java/com/oronaminc/join/Web57OronaminCBeApplication.java
  src/main/java/com/oronaminc/join/global/config/WebSocketConfig.java
  src/main/java/com/oronaminc/join/global/dto/WriterDto.java
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/member/api/MemberController.java
  src/main/java/com/oronaminc/join/member/dao/MemberJpaRepository.java
  src/main/java/com/oronaminc/join/member/dao/MemberRepository.java
  src/main/java/com/oronaminc/join/member/domain/Member.java
  src/main/java/com/oronaminc/join/member/security/AuthService.java
  src/main/java/com/oronaminc/join/member/service/MemberService.java
  src/main/java/com/oronaminc/join/participant/dao/ParticipantRepository.java
  src/main/java/com/oronaminc/join/participant/domain/Participant.java
  src/main/java/com/oronaminc/join/question/dao/QuestionRepository.java
  src/main/java/com/oronaminc/join/question/domain/Question.java
  src/main/java/com/oronaminc/join/question/dto/QuestionCreateRequest.java
  src/main/java/com/oronaminc/join/question/dto/QuestionCreateResponse.java
  src/main/java/com/oronaminc/join/question/mapper/QuestionMapper.java
  src/main/java/com/oronaminc/join/question/service/QuestionService.java
  src/main/java/com/oronaminc/join/room/dao/RoomRepository.java
  src/main/java/com/oronaminc/join/room/domain/Room.java
  src/main/java/com/oronaminc/join/websocket/api/QuestionWebsocketController.java
  src/main/java/com/oronaminc/join/websocket/config/CustomHandshakeHandler.java
  src/main/java/com/oronaminc/join/websocket/config/WebSocketConfig.java
  src/test/java/com/oronaminc/join/question/service/QuestionServiceTests.java
Labels: feat

#18 [Feat]: 발표방 생성, 팀원 이메일 검증 API
  .gitignore
  src/main/java/com/oronaminc/join/answer/domain/Answer.java
  src/main/java/com/oronaminc/join/document/dao/DocumentJpaRepository.java
  src/main/java/com/oronaminc/join/document/domain/Document.java
  src/main/java/com/oronaminc/join/document/service/DocumentService.java
  src/main/java/com/oronaminc/join/emoji/domain/Emoji.java
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/member/api/MemberController.java
  src/main/java/com/oronaminc/join/member/dao/MemberJpaRepository.java
  src/main/java/com/oronaminc/join/member/dao/MemberRepository.java
  src/main/java/com/oronaminc/join/member/domain/Member.java
  src/main/java/com/oronaminc/join/member/dto/ExistsMemberRequest.java
  src/main/java/com/oronaminc/join/member/dto/ExistsMemberResponse.java
  src/main/java/com/oronaminc/join/member/security/AuthService.java
  src/main/java/com/oronaminc/join/member/service/MemberService.java
  src/main/java/com/oronaminc/join/participant/domain/Participant.java
  src/main/java/com/oronaminc/join/participant/service/ParticipantService.java
  src/main/java/com/oronaminc/join/participant/util/ParticipantMapper.java
  src/main/java/com/oronaminc/join/question/domain/Question.java
  src/main/java/com/oronaminc/join/question/mapper/QuestionMapper.java
  src/main/java/com/oronaminc/join/room/api/RoomController.java
  src/main/java/com/oronaminc/join/room/dao/RoomRepository.java
  src/main/java/com/oronaminc/join/room/domain/Room.java
  src/main/java/com/oronaminc/join/room/dto/CreateRoomRequest.java
  src/main/java/com/oronaminc/join/room/dto/CreateRoomResponse.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/java/com/oronaminc/join/room/util/CodeGenerator.java
  src/main/java/com/oronaminc/join/room/util/RoomMapper.java
Labels: feat

#23 feat: 비밀 코드 방 입장, 상세 조회 API 구현
  src/main/java/com/oronaminc/join/document/dao/DocumentRepository.java
  src/main/java/com/oronaminc/join/document/service/DocumentService.java
  src/main/java/com/oronaminc/join/emoji/repository/EmojiRepository.java
  src/main/java/com/oronaminc/join/emoji/service/EmojiService.java
  src/main/java/com/oronaminc/join/member/service/MemberService.java
  src/main/java/com/oronaminc/join/participant/dao/ParticipantRepository.java
  src/main/java/com/oronaminc/join/participant/service/ParticipantService.java
  src/main/java/com/oronaminc/join/room/api/RoomController.java
  src/main/java/com/oronaminc/join/room/dao/RoomRepository.java
  src/main/java/com/oronaminc/join/room/dto/JoinRoomRequest.java
  src/main/java/com/oronaminc/join/room/dto/JoinRoomResponse.java
  src/main/java/com/oronaminc/join/room/dto/RoomDetailResponse.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/java/com/oronaminc/join/room/util/RoomMapper.java
Labels: feat

#28 feat: 수정, 삭제, 상태 변경 API 구현
  src/main/java/com/oronaminc/join/answer/dao/AnswerRepository.java
  src/main/java/com/oronaminc/join/answer/service/AnswerService.java
  src/main/java/com/oronaminc/join/document/dao/DocumentRepository.java
  src/main/java/com/oronaminc/join/document/service/DocumentService.java
  src/main/java/com/oronaminc/join/emoji/repository/EmojiRepository.java
  src/main/java/com/oronaminc/join/emoji/service/EmojiService.java
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/participant/dao/ParticipantRepository.java
  src/main/java/com/oronaminc/join/participant/service/ParticipantService.java
  src/main/java/com/oronaminc/join/question/dao/QuestionRepository.java
  src/main/java/com/oronaminc/join/question/service/QuestionService.java
  src/main/java/com/oronaminc/join/room/api/RoomController.java
  src/main/java/com/oronaminc/join/room/domain/Room.java
  src/main/java/com/oronaminc/join/room/dto/RoomUpdateInfoResponse.java
  src/main/java/com/oronaminc/join/room/dto/RoomUpdateRequest.java
  src/main/java/com/oronaminc/join/room/dto/RoomUpdateStatusRequest.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/java/com/oronaminc/join/room/util/RoomMapper.java
Labels: feat

#30 feat: 개발용 회원 API
  src/main/java/com/oronaminc/join/global/dev/DevController.java
  src/main/java/com/oronaminc/join/global/dev/DevJoinRequest.java
  src/main/java/com/oronaminc/join/global/dev/DevLoginRequest.java
  src/main/java/com/oronaminc/join/member/security/AuthService.java
  src/main/java/com/oronaminc/join/member/security/SecurityConfig.java
Labels: feat

#57 feat: 발표방 참여 및 입장 인원 계산 로직
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/room/domain/RoomStatus.java
  src/main/java/com/oronaminc/join/room/dto/RoomExitEvent.java
  src/main/java/com/oronaminc/join/room/dto/RoomJoinResponse.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/java/com/oronaminc/join/room/util/RoomMapper.java
  src/main/java/com/oronaminc/join/websocket/api/RoomWebsocketController.java
  src/main/java/com/oronaminc/join/websocket/api/WebSocketExceptionHandler.java
  src/main/java/com/oronaminc/join/websocket/config/CustomWebSocketHandlerDecorator.java
  src/main/java/com/oronaminc/join/websocket/config/ParticipantEventHandler.java
  src/main/java/com/oronaminc/join/websocket/config/ParticipantManager.java
  src/main/java/com/oronaminc/join/websocket/config/WebSocketConfig.java
  src/main/java/com/oronaminc/join/websocket/config/WebsocketSessionManager.java
Labels: feat

#64 feat: 참가자 퇴장 시간 저장 및 웹소켓, 발표방 리팩토링
  src/main/java/com/oronaminc/join/document/service/DocumentService.java
  src/main/java/com/oronaminc/join/member/domain/Member.java
  src/main/java/com/oronaminc/join/member/security/AuthService.java
  src/main/java/com/oronaminc/join/member/util/MemberMapper.java
  src/main/java/com/oronaminc/join/participant/domain/Participant.java
  src/main/java/com/oronaminc/join/participant/event/ParticipantEventHandler.java
  src/main/java/com/oronaminc/join/participant/service/ParticipantService.java
  src/main/java/com/oronaminc/join/question/dao/QuestionRepository.java
  src/main/java/com/oronaminc/join/question/service/QuestionReader.java
  src/main/java/com/oronaminc/join/question/service/QuestionService.java
  src/main/java/com/oronaminc/join/room/api/RoomController.java
  src/main/java/com/oronaminc/join/room/dto/ReportResponse.java
  src/main/java/com/oronaminc/join/room/dto/RoomUpdateStatusRequest.java
  src/main/java/com/oronaminc/join/room/dto/TopQnAResponse.java
  src/main/java/com/oronaminc/join/room/event/RoomDeleteEvent.java
  src/main/java/com/oronaminc/join/room/event/RoomEventHandler.java
  src/main/java/com/oronaminc/join/room/event/RoomExitEvent.java
  src/main/java/com/oronaminc/join/room/service/RoomReader.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/java/com/oronaminc/join/room/util/RoomMapper.java
  src/main/java/com/oronaminc/join/websocket/api/RoomWebsocketController.java
  src/main/java/com/oronaminc/join/websocket/api/WebSocketExceptionHandler.java
  src/main/java/com/oronaminc/join/websocket/config/WebSocketConfig.java
  src/main/java/com/oronaminc/join/websocket/handshake/CustomHandshakeHandler.java
  src/main/java/com/oronaminc/join/websocket/session/CurrentParticipantEventHandler.java
  src/main/java/com/oronaminc/join/websocket/session/CurrentParticipantManager.java
  src/main/java/com/oronaminc/join/websocket/session/CustomWebSocketHandlerDecorator.java
  src/main/java/com/oronaminc/join/websocket/session/WebsocketSessionManager.java
  src/main/java/com/oronaminc/join/websocket/stomp/StompErrorHandler.java
  src/main/java/com/oronaminc/join/websocket/stomp/StompPrincipal.java
Labels: feat, refactor

#80 feat: 발표방 캐싱 및 인덱싱 적용 feat 새로운 기능 추가
  build.gradle
  src/main/java/com/oronaminc/join/emoji/service/EmojiFacade.java
  src/main/java/com/oronaminc/join/global/config/CacheConfig.java
  src/main/java/com/oronaminc/join/global/config/CacheType.java
  src/main/java/com/oronaminc/join/global/dev/DevController.java
  src/main/java/com/oronaminc/join/global/dev/HealthController.java
  src/main/java/com/oronaminc/join/member/security/SecurityConfig.java
  src/main/java/com/oronaminc/join/room/domain/Room.java
  src/main/java/com/oronaminc/join/room/dto/CreateRoomRequest.java
  src/main/java/com/oronaminc/join/room/service/RoomReader.java
  src/main/java/com/oronaminc/join/room/service/RoomService.java
  src/main/resources/static/favicon.ico
  src/test/java/com/oronaminc/join/emoji/service/EmojiFacadeTests.java
  src/test/java/com/oronaminc/join/room/service/RoomCacheTests.java
  src/test/resources/application.yml
Labels: feat, test

#91 feat: 카카오 로그인 재시도 로직, 방 참가자 관리 동시성 수정
  build.gradle
  src/main/java/com/oronaminc/join/global/config/RestTemplateConfig.java
  src/main/java/com/oronaminc/join/room/api/RoomController.java
  src/main/java/com/oronaminc/join/websocket/session/CurrentParticipantManager.java
Labels: feat, refactor

#96 fix: MemberController 수정
  src/main/java/com/oronaminc/join/member/api/MemberController.java
  src/main/java/com/oronaminc/join/member/security/AuthController.java
  src/main/java/com/oronaminc/join/member/util/MemberMapper.java
Labels: fix

#131 fix: cors 메서드 수정
  src/main/java/com/oronaminc/join/global/exception/ErrorCode.java
  src/main/java/com/oronaminc/join/member/security/SecurityConfig.java
Labels: fix
